apiVersion: batch/v1
kind: Job
metadata:
  name: postgres-init-job1
spec:
  ttlSecondsAfterFinished: 60  # Удалит Job через 60 секунд после завершения
  template:
    spec:
      containers:
        - name: postgres-init1
          image: postgres:16
          env:
            - name: PGPASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret # Название секрета
                  key: POSTGRES_PASSWORD # Поле с паролем
          command:
            - "sh"
            - "-c"
            - "psql -h postgres-shards-1.postgres -U postgres -d postgres -f /init1.sql"
          volumeMounts:
            - name: init-script1
              mountPath: /init1.sql
              subPath: init1.sql
      volumes:
        - name: init-script1
          configMap:
            name: orders-replica-shards1-config
            items:
              - key: init1.sql
                path: init1.sql
      restartPolicy: OnFailure
